### ISSUE TITLE
demo  load ck error

### ISSUE THREAD

**Issue by changquanyou** [360CVGroup/360VL#2]
>>> from transformers import AutoModelForCausalLM, AutoTokenizer
>>> import torch
>>> from PIL import Image
>>> checkpoint = "qihoo360/360VL-8B"
>>> model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16, device_map='cuda', trust_remote_code=True).eval()
/home/users/xiongxinlei/.conda/envs/qwen/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/xiongxinlei/.conda/envs/qwen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/home/users/xiongxinlei/.conda/envs/qwen/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3375, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 631, in __init__
    self.model = QH360_VL_LlamaModel(config)
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 622, in __init__
    super(QH360_VL_LlamaModel, self).__init__(config)
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 448, in __init__
    self.mm_projector_ctt = build_vision_projector(config)
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 422, in build_vision_projector
    abstractor = build_honeybee_projector(honeybee_config,projector_type,num_tokens,lm_hidden_size)
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 399, in build_honeybee_projector
    abstractor = {
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 284, in __init__
    self.build_net()
  File "/home/users/xiongxinlei/.cache/huggingface/modules/transformers_modules/360VL-8B/modeling_360vl.py", line 334, in build_net
    depth = self.config.depth
  File "/home/users/xiongxinlei/.conda/envs/qwen/lib/python3.10/site-packages/transformers/configuration_utils.py", line 265, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'HoneybeeVisualProjectorConfig' object has no attribute 'depth'

**Comment by changquanyou** [comment]
1. 新增配置文件：visual_projector_config.json(config.json中的visual_projector_config内容)
2. config.json 中更改配置：   "mm_projector_config": "qihoo360/360VL-8B/visual_projector_config.json"
