### ISSUE TITLE
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

### ISSUE THREAD

**Issue by changquanyou** [360CVGroup/360VL#3]
![image](https://github.com/360CVGroup/360VL/assets/9205633/96cf9931-b1fa-45f5-9b09-290f9af0498c)
错误信息如下：
2024-05-19 20:02:48 | WARNING | transformers.generation.utils | Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.
2024-05-19 20:02:48 | ERROR | stderr | Exception in thread Thread-3 (generate):
2024-05-19 20:02:48 | ERROR | stderr | Traceback (most recent call last):
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-05-19 20:02:48 | ERROR | stderr |     self.run()
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/threading.py", line 953, in run
2024-05-19 20:02:48 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-05-19 20:02:48 | ERROR | stderr |     return func(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/transformers/generation/utils.py", line 1592, in generate
2024-05-19 20:02:48 | ERROR | stderr |     return self.sample(
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/transformers/generation/utils.py", line 2696, in sample
2024-05-19 20:02:48 | ERROR | stderr |     outputs = self(
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-05-19 20:02:48 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-05-19 20:02:48 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
2024-05-19 20:02:48 | ERROR | stderr |     output = module._old_forward(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "/home/disk2/mobile_agent/360VL-master/qh360_vl/model/language_model/QH360_VL_llama.py", line 80, in forward
2024-05-19 20:02:48 | ERROR | stderr |     outputs = self.model(
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2024-05-19 20:02:48 | ERROR | stderr |     return self._call_impl(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2024-05-19 20:02:48 | ERROR | stderr |     return forward_call(*args, **kwargs)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 993, in forward
2024-05-19 20:02:48 | ERROR | stderr |     causal_mask = self._update_causal_mask(attention_mask, inputs_embeds)
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1059, in _update_causal_mask
2024-05-19 20:02:48 | ERROR | stderr |     if attention_mask is not None and 0.0 in attention_mask:
2024-05-19 20:02:48 | ERROR | stderr |   File "lib/python3.10/site-packages/torch/_tensor.py", line 1059, in __contains__
2024-05-19 20:02:48 | ERROR | stderr |     return (element == self).any().item()  # type: ignore[union-attr]
2024-05-19 20:02:48 | ERROR | stderr | RuntimeError: CUDA error: device-side assert triggered
2024-05-19 20:02:48 | ERROR | stderr | CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2024-05-19 20:02:48 | ERROR | stderr | For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2024-05-19 20:02:48 | ERROR | stderr | Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2024-05-19 20:02:48 | ERROR | stderr | 
2024-05-19 20:02:51 | INFO | model_worker | Send heart beat. Models: ['360VL-8B']. Semaphore: Semaphore(value=4, locked=False). global_counter: 1
2024-05-19 20:03:03 | INFO | stdout | Caught Unknown Error
2024-05-19 20:03:03 | INFO | model_worker | Send heart beat. Models: ['360VL-8B']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1
2024-05-19 20:03:06 | INFO | model_worker | Send heart beat. Models: ['360VL-8B']. Semaphore: Semaphore(value=5, locked=False). global_counter: 1

**Comment by binwang777** [comment]
Hi, I guess it is a problem with the transformers version. Please switch to 4.37.2 and try it.

**Comment by changquanyou** [comment]
current version is 4.38.2, and the demo is successed, I try the 4.37.2, it's failed too
